
package br.gov.caixa.sibar.consulta_cobranca_bancaria.boleto;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Consulta_Cobranca_Bancaria_Boleto", targetNamespace = "http://caixa.gov.br/sibar/consulta_cobranca_bancaria/boleto")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    br.gov.caixa.sibar.ObjectFactory.class,
    br.gov.caixa.sibar.consulta_cobranca_bancaria.boleto.ObjectFactory.class
})
public interface ConsultaCobrancaBancariaBoleto {


    /**
     * 
     * @param parameters
     * @return
     *     returns br.gov.caixa.sibar.consulta_cobranca_bancaria.boleto.SERVICOSAIDANEGOCIALTYPE
     */
    @WebMethod(operationName = "CONSULTA_BOLETO", action = "http://caixa.gov.br/sibar/consulta_cobranca_bancaria/boleto/NewOperation")
    @WebResult(name = "SERVICO_SAIDA", targetNamespace = "http://caixa.gov.br/sibar/consulta_cobranca_bancaria/boleto", partName = "parameters")
    public SERVICOSAIDANEGOCIALTYPE consultaBOLETO(
        @WebParam(name = "SERVICO_ENTRADA", targetNamespace = "http://caixa.gov.br/sibar/consulta_cobranca_bancaria/boleto", partName = "parameters")
        SERVICOENTRADANEGOCIALTYPE parameters);

}
